### PR TITLE
Update repo list and add descriptions in README

### PR DESCRIPTION
**Pull request by bhousel**
Just updates to the repository list with latest info and adds descriptions

### CODE REVIEW

**Comment by jfirebaugh** [comment]
Wordsmithing for the renderer descriptions -- we should apply these to the upstream repo descriptions:
- [mapbox-gl-js](https://github.com/mapbox/mapbox-gl-js) - Render Mapbox styles in the browser using JavaScript and WebGL.
- [mapbox-gl-native](https://github.com/mapbox/mapbox-gl-native) - Render Mapbox styles in mobile, desktop, and node applications using C++ and OpenGL.

@tmcw Do we want to advertise carto-to-gl, or avoid getting anyone's hopes up?

**Comment by tmcw** [comment]
Don't advertise carto-to-gl, it'd take a few months of development to be usable.

**Comment by tmcw** [comment]
Err also I made [a standalone repo for this a while ago](https://github.com/mapbox/awesome-vector-tiles) and it seems like a better place than this readme.

**Comment by jfirebaugh** [comment]
@tmcw That's a different list -- this is a list of the Mapbox repositories relating to Mapbox GL.

**Comment by bhousel** [comment]
I just read that as, @tmcw wanted to move `carto-to-gl` to the other list..

**Pull request merged**
